app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from app.api.routes import api
from flask_cors import CORS

from models import loginManager, db
from app.site.routes import site
from app.authentication.routes import auth  
app = Flask(__name__)
CORS(app)
app.register_blueprint(auth)
app.register_blueprint(site)
app.register_blueprint(api)
app.config.from_object(Config)
#db = SQLAlchemy(app)
migrate = Migrate(app, db)
#loginManager = LoginManager(app)
db.init_app(app)
loginManager.init_app(app)

app/api/routes.py
from flask import Blueprint, render_template, request, jsonify, flash, redirect, url_for
from models import db, User, Car, car_schema, cars_schema, loginManager
from helpers import token_required
from forms import PostCar
from flask_login import current_user, login_required


api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/inventory', methods=['POST'])
@token_required
def create_car(current_user_token):
    make = request.json['make']
    model = request.json['model']
    year = request.json['year']
    color = request.json['color']
    price = request.json['price']
    mileage = request.json['mileage']
    seller_id = current_user_token.id

    car = Car(make, model, year, color, price,mileage, seller_id=seller_id)

    db.session.add(car)
    db.session.commit()

    response = car_schema.dump(car)
    return jsonify(response)

@api.route('/inventory', methods=['GET'])
@token_required
def get_cars(current_user_token):
    owner = current_user_token.id
    cars = Car.query.filter_by(seller_id=owner).all()
    response = cars_schema.dump(cars)
    return jsonify(response)    

@api.route('/inventory/<id>', methods=['GET'])
@token_required
def get_car(current_user_token, id):
    current_user_token = current_user_token.token
    id = Car.query.get(id)
    response = car_schema.dump(id)
    return jsonify(response)



@api.route('/inventory/<id>', methods=['PUT', 'POST'])
@token_required
def update_car(current_user_token, id):
    car = Car.query.get(id)

    car.make = request.json['make']
    car.model = request.json['model']
    car.year = request.json['year']
    car.color = request.json['color']
    car.price = request.json['price']
    car.mileage = request.json['mileage']
    car.seller_id = current_user_token.id

    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)

@api.route('/inventory/<id>', methods=['DELETE'])
@token_required
def delete_car(current_user_token, id):
    id = request.json['id']
    current_user_token = current_user_token.token
    car = Car.query.get(id)
    db.session.delete(car)
    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)

app/authentication/routes.py
from forms import SignIn, SignUp
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models import db, User, check_password_hash
from flask_login import login_user, current_user, logout_user, login_required, LoginManager
  


auth = Blueprint('auth', __name__, template_folder='auth_templates')



@auth.route("/signup", methods=['GET', 'POST'])
def signup():
    form = SignUp()
    try:
        if request.method == 'POST': 
            #and form.validate_on_submit():
            first_name = form.first_name.data
            last_name = form.last_name.data
            email = form.email.data
            password = form.password.data
            print(first_name, last_name, email, password)
            
            user = User(first_name, last_name, email, password, g_auth_verify=False)
            db.session.add(user)
            db.session.commit()
            flash(f'Account created for {form.first_name.data}!', 'success')
            return redirect(url_for('auth.signin'))
    except:
        raise Exception("Invalid Form Data: Please Check Your Form")
    return render_template('signup.html', form=form)

@auth.route("/signin", methods=['GET', 'POST'])
def signin():
    form = SignIn()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)
            
            user = User.query.filter(User.email==email).first()
            if user and check_password_hash(user.password, password):
                login_user(user)
                flash('You have successfully logged in.', 'success')
                return redirect(url_for('site.home_page'))
    except:
        raise Exception("Invalid Form Data: Please Check Your Form")
    return render_template('signin.html', form=form)

@auth.route("/signout")
def signout():
    logout_user()
    return redirect(url_for('site.home_page'))

app/site/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect, request
from forms import UpdateProfile
from flask_login import current_user
from flask_login import login_required
from models import db, User




site = Blueprint('site', __name__, template_folder='site_templates')


@site.route("/")
def home_page():
    return render_template('home.html')

@site.route('/inventory')
def inventory_page():
    return render_template('inventory.html')



@site.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = UpdateProfile()
    if form.validate_on_submit():
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('site.profile'))
    elif request.method == 'GET':
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
        form.email.data = current_user.email
    return render_template('profile.html',  form=form, name=current_user.first_name, user=current_user)

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <title>Summit Auto Group</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}"

</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <div class="d-flex nav-link align-self-center p-3 ">
                <a class="nav-link align-self-center p-3 " href="{{ url_for('site.home_page')}}">Summit Auto Group</a>
                <a class="nav-link align-self-center p-3" href="{{ url_for('site.profile')}}">Profile</a>
            </div>
            
            <ul class="navbar-nav">
              {% if current_user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="/signout">Sign Out</a>
              </li>
              {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.signin')}}">Sign In</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.signup')}}">Sign Up</a>
               </li>
              {% endif %} 
            </ul>
        </div>
    </nav>
    
    
 </header>
  <main>
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
         <div class="alert alert-{{ category }}">
          {{ message }}
        </div>
        {%endfor%}
      {% endif %}
    {% endwith %}
    {% block content %}
    {% endblock %}
  </main>
  <footer>
    <!-- place footer here -->
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>

</html>